//堀:~/pnotes/Shouda_Tsuyano_A1257/P5580/sample_next_app/src/app/layout.tsx
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
const geistSans = 
localFont(
  {
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
  }
);
//**********************************************************************
const geistMono = 
localFont(
  {
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
  }
);
//**********************************************************************
export const metadata: Metadata = 
{
  title: 'Create Next App',
  description: 'Generated by create next app',
};
//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function RootLayout( 
  {children}: Readonly<{children: React.ReactNode}>
){
  console.log('-- RootLayout()#1');//Tracing.
  return (
    <html lang='ja'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
export default RootLayout
